sudo: required
language: bash
services:
  - docker
branches:
  only:
    - master
env:
  global:
    - DOCKER_REPO='zephinzer/alpine-node'
script:
  - docker build -t next .
after_success:
  - VERSION=$(./scripts/versioning/get-next -q)
  - docker login -u $DHUSER -p $DHPASS
  - docker tag next ${}
  - docker tag ${DOCKER_REPO}:${VERSION} ${DOCKER_REPO}:latest
  - docker push ${DOCKER_REPO}:${VERSION}
  - docker logout
  - git checkout release
  - git rebase ${TRAVIS_BRANCH}
  - git reset --hard ${TRAVIS_COMMIT}
  - ./scripts/versioning/iterate -i -q
  - git push -q https://zephinzer:${GITHUB_TOKEN}@github.com/zephinzer/docker-image-alpine-node.git --tags