sudo: required
language: bash
services:
  - docker
branches:
  only:
    - master
env:
  global:
    - BUILD_VERSION=$(./scripts/versioning/get-next -q)
    - DOCKER_REPO='zephinzer/alpine-node'
    - NEXT_ARGON='next_argon'
    - NEXT_BORON='next_boron'
    - NEXT_CARBON='next_carbon'
    - TAG_ARGON='argon'
    - TAG_BORON='boron'
    - TAG_CARBON='carbon'
    - DH_TAGS_URL=https://index.docker.io/v1/repositories/zephinzer/alpine-node/tags/
notifications:
  email:
    - dev@joeir.net
stages:
  - build
  - test-react-development
  - publish
before_script:
  - docker login -u $DHUSER -p $DHPASS
after_script:
  - docker logout
jobs:
  include: # <codename>-<node_version>, <build_version>-<codename>, latest-<codename>
    - stage: build
      env:
        - building=argon
      script:
        - ./scripts/build/setup
        - ./scripts/ci/build argon
        - ./scripts/build/teardown
    - stage: build
      env:
        - building=boron
      script:
        - ./scripts/build/setup
        - ./scripts/ci/build boron
        - ./scripts/build/teardown
    - stage: build
      env:
        - building=carbon
      script:
        - ./scripts/build/setup
        - ./scripts/ci/build carbon
        - ./scripts/build/teardown
    - stage: test-react-development
      env:
        - FRAMEWORK=react-development
        - REMOTE_TAG=latest-argon
        - LOCAL_TAG=test_argon_react
      script:
        - docker pull ${DOCKER_REPO}:${REMOTE_TAG};
        - ./test/.scripts/setup ${FRAMEWORK} ${REMOTE_TAG};
        - docker build -f ./test/${FRAMEWORK}/${REMOTE_TAG}.Dockerfile -t ${LOCAL_TAG} ./test/${FRAMEWORK};
        - docker run ${LOCAL_TAG};
        - ./test/.scripts/teardown ${FRAMEWORK};
    - stage: test-react-development
      env:
        - FRAMEWORK=react-development
        - REMOTE_TAG=latest-boron
        - LOCAL_TAG=test_boron_react
      script:
        - docker pull ${DOCKER_REPO}:${REMOTE_TAG};
        - ./test/.scripts/setup ${FRAMEWORK} ${REMOTE_TAG};
        - docker build -f ./test/${FRAMEWORK}/${REMOTE_TAG}.Dockerfile -t ${LOCAL_TAG} ./test/${FRAMEWORK};
        - docker run ${LOCAL_TAG};
        - ./test/.scripts/teardown ${FRAMEWORK};
    - stage: test-react-development
      env:
        - FRAMEWORK=react-development
        - REMOTE_TAG=latest-carbon
        - LOCAL_TAG=test_carbon_react
      script:
        - docker pull ${DOCKER_REPO}:${REMOTE_TAG};
        - ./test/.scripts/setup ${FRAMEWORK} ${REMOTE_TAG};
        - docker build -f ./test/${FRAMEWORK}/${REMOTE_TAG}.Dockerfile -t ${LOCAL_TAG} ./test/${FRAMEWORK};
        - docker run ${LOCAL_TAG};
        - ./test/.scripts/teardown ${FRAMEWORK};
    - stage: publish
      script:
        - |
          if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then \
            git checkout ${TRAVIS_BRANCH} && \
            git reset --hard ${TRAVIS_COMMIT} && \
            ./scripts/versioning/iterate -i -q && \
            git push -q https://zephinzer:${GITHUB_TOKEN}@github.com/zephinzer/docker-image-alpine-node.git --tags; \
          fi;
      after_success:
        - |
          if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then \
            git checkout ${TRAVIS_BRANCH} && \
            git remote -v && \
            git pull && \
            git fetch origin && \
            git branch && \
            git checkout release && \
            git rebase ${TRAVIS_BRANCH} && \
            git push -q https://zephinzer:${GITHUB_TOKEN}@github.com/zephinzer/docker-image-alpine-node.git origin release; \
          fi;