sudo: required
language: bash
services:
  - docker
stages:
  - dockerBuild
  - publishToGithub
jobs:
  include:
    - stage: dockerBuild
      script:
        - docker build .
    - stage: publishToGithub
      script:
        - git checkout ${TRAVIS_BRANCH}
        - git remote remove origin
        - git remote add origin git@github.com:zephinzer/docker-image-alpine-node.git
        - git reset --hard ${TRAVIS_COMMIT}
        - ls -lA ./scripts/versioning
        - bash ./scripts/versioning/iterate -i -q
        - git push -q https://zephinzer:${GITHUB_TOKEN}@github.com/zephinzer/docker-image-alpine-node.git --tags