sudo: required
language: bash
services:
  - docker
stages:
  - dockerBuild
  - publishToGithub
jobs:
  include:
    - stage: dockerBuild
      script:
        - docker build .
    - stage: publishToGithub
      script:
        - mkdir -p ~/.ssh
        - echo ${SSH_DEPLOY_KEY} > ~/.ssh/known_hosts
        - git checkout ${TRAVIS_BRANCH}
        - git fetch origin ${TRAVIS_BRANCH}
        - git reset --hard ${TRAVIS_COMMIT}
        - ./scripts/versioning/iterate -i -q
        - git push --tags