sudo: required
language: bash
services:
  - docker
branches:
  only:
    - master
env:
  global:
    - BUILD_VERSION=$(./scripts/versioning/get-next -q)
    - DOCKER_REPO='zephinzer/alpine-node'
    - NEXT_ARGON='next_argon'
    - NEXT_BORON='next_boron'
    - NEXT_CARBON='next_carbon'
    - TAG_ARGON='argon'
    - TAG_BORON='boron'
    - TAG_CARBON='carbon'
    - DH_TAGS_URL=https://index.docker.io/v1/repositories/zephinzer/alpine-node/tags/
notifications:
  email:
    - dev@joeir.net
stages:
  - build
  - test
  - publish
jobs:
  include: # <codename>-<node_version>, <build_version>-<codename>, latest-<codename>
    - stage: build
      env:
        - TAG_NAME=argon
      script:
        - ./scripts/ci/build ${TAG_NAME}
    - stage: build
      env:
        - TAG_NAME=boron
      script:
        - ./scripts/ci/build ${TAG_NAME}
    - stage: build
      env:
        - TAG_NAME=carbon
      script:
        - ./scripts/ci/build ${TAG_NAME}
    - stage: test
      env:
        - FRAMEWORK=react-development
        - REMOTE_TAG=latest-argon
        - LOCAL_TAG=test_argon_react
      script:
        - ./scripts/ci/test ${FRAMEWORK} ${REMOTE_TAG} ${LOCAL_TAG}
    - stage: test
      env:
        - FRAMEWORK=react-development
        - REMOTE_TAG=latest-boron
        - LOCAL_TAG=test_boron_react
      script:
        - ./scripts/ci/test ${FRAMEWORK} ${REMOTE_TAG} ${LOCAL_TAG}
    - stage: test
      env:
        - FRAMEWORK=react-development
        - REMOTE_TAG=latest-carbon
        - LOCAL_TAG=test_carbon_react
      script:
        - ./scripts/ci/test ${FRAMEWORK} ${REMOTE_TAG} ${LOCAL_TAG}
    - stage: test
      env:
        - FRAMEWORK=node-development
        - REMOTE_TAG=latest-argon
        - LOCAL_TAG=test_argon_node
      script:
        - ./scripts/ci/test ${FRAMEWORK} ${REMOTE_TAG} ${LOCAL_TAG}
    - stage: test
      env:
        - FRAMEWORK=node-development
        - REMOTE_TAG=latest-boron
        - LOCAL_TAG=test_boron_node
      script:
        - ./scripts/ci/test ${FRAMEWORK} ${REMOTE_TAG} ${LOCAL_TAG}
    - stage: test
      env:
        - FRAMEWORK=node-development
        - REMOTE_TAG=latest-carbon
        - LOCAL_TAG=test_carbon_node
      script:
        - ./scripts/ci/test ${FRAMEWORK} ${REMOTE_TAG} ${LOCAL_TAG}
    - stage: publish
      script:
        - ./scripts/ci/publish