sudo: required
language: bash
services:
  - docker
branches:
  only:
    - master
env:
  global:
    - BUILD_VERSION=$(./scripts/versioning/get-next -q)
    - DOCKER_REPO='zephinzer/alpine-node'
    - NEXT_ARGON='next_argon'
    - NEXT_BORON='next_boron'
    - NEXT_CARBON='next_carbon'
    - TAG_ARGON='argon'
    - TAG_BORON='boron'
    - TAG_CARBON='carbon'
notifications:
  email:
    - dev@joeir.net
stages:
  - build
  - test
  - publish
before_script:
  - docker login -u $DHUSER -p $DHPASS
after_script:
  - docker logout
jobs:
  include: # <codename>-<node_version>, <build_version>-<codename>, latest-<codename>
    - stage: build
      script:
        - ./scripts/build/setup
        - NODE_VERSION=$(cat ./${TAG_ARGON}.Version);
        - docker build -t ${NEXT_ARGON} -f argon.Dockerfile .
        - docker tag ${NEXT_ARGON} ${DOCKER_REPO}:${TAG_ARGON}-${NODE_VERSION}
        - docker tag ${NEXT_ARGON} ${DOCKER_REPO}:${BUILD_VERSION}-${TAG_ARGON}
        - docker tag ${NEXT_ARGON} ${DOCKER_REPO}:latest-${TAG_ARGON}
        - ./scripts/build/teardown
    - stage: build
      script:
        - ./scripts/build/setup
        - NODE_VERSION=$(cat ./${TAG_BORON}.Version);
        - docker build -t ${NEXT_BORON} -f boron.Dockerfile .
        - docker tag ${NEXT_BORON} ${DOCKER_REPO}:${TAG_BORON}-${NODE_VERSION}
        - docker tag ${NEXT_BORON} ${DOCKER_REPO}:${BUILD_VERSION}-${TAG_BORON}
        - docker tag ${NEXT_BORON} ${DOCKER_REPO}:latest-${TAG_BORON}
        - ./scripts/build/teardown
    - stage: build
      script:
        - ./scripts/build/setup
        - NODE_VERSION=$(cat ./${TAG_CARBON}.Version);
        - docker build -t ${NEXT_CARBON} -f carbon.Dockerfile .
        - docker tag ${NEXT_CARBON} ${DOCKER_REPO}:${TAG_CARBON}-${NODE_VERSION}
        - docker tag ${NEXT_CARBON} ${DOCKER_REPO}:${BUILD_VERSION}-${TAG_CARBON}
        - docker tag ${NEXT_CARBON} ${DOCKER_REPO}:latest-${TAG_CARBON}
        - ./scripts/build/teardown
    - stage: test
      script:
        - docker image ls -a
    - stage: publish
      script:
        - docker push ${DOCKER_REPO}:${BUILD_VERSION}${TAG_CARBON}
        - docker push ${DOCKER_REPO}:${BUILD_VERSION}${TAG_BORON}
        - docker push ${DOCKER_REPO}:${BUILD_VERSION}${TAG_ARGON}
    - stage: publish
      script:
        - git checkout ${TRAVIS_BRANCH}
        - git reset --hard ${TRAVIS_COMMIT}
        - ./scripts/versioning/iterate -i -q
        - git push -q https://zephinzer:${GITHUB_TOKEN}@github.com/zephinzer/docker-image-alpine-node.git --tags
        - git fetch origin release
        - git checkout release
        - git rebase ${TRAVIS_BRANCH}
        - git push -q https://zephinzer:${GITHUB_TOKEN}@github.com/zephinzer/docker-image-alpine-node.git