sudo: required
language: bash
services:
  - docker
stages:
  - dockerBuild
  - publishToGithub
before_install:
  - mkdir -p ~/.ssh
  - echo ${SSH_DEPLOY_KEY} > ~/.ssh/id_rsa_github_docker_image_alpine_node_deploy
  - chmod 600 ~/.ssh/id_rsa_github_docker_image_alpine_node_deploy
  - ssh-keyscan -H 'github.com,192.30.253.112' >> ~/.ssh/known_hosts
jobs:
  include:
    # - stage: dockerBuild
    #   script:
    #     - docker build .
    - stage: publishToGithub
      script:
        - git checkout ${TRAVIS_BRANCH}
        - git remote remove origin
        - git remote add origin git@github.com:zephinzer/docker-image-alpine-node.git
        - git reset --hard ${TRAVIS_COMMIT}
        - bash ./scripts/versioning/iterate -i -q
        - git push --tags